# Pipleine Script for building Web AEM for AMS Corp

variables:
  buildEnv: dev

trigger:
- development
- feature/*
- release/*
- master

pr:
- master
- developemt
- release/*

pool:
 name: Linux-AgentPool
 demands:
   - agent.os -equals Linux
   - agent_name  -equals linux-survivor   

steps:
- checkout: self
  clean: true
  persistCredentials: true

- script: |
    echo "Building AMS paclife-dsys-ui"
    ls -al
    pwd    
    echo $(Agent.TempDirectory)

- task: ArtifactoryMaven@2
  inputs:
    mavenPomFile: 'pom.xml'
    goals: 'clean install'
    artifactoryResolverService: 'JFrog'
    targetResolveReleaseRepo: 'web-maven'
    targetResolveSnapshotRepo: 'web-maven'
    artifactoryDeployService: 'JFrog'
    targetDeployReleaseRepo: 'web-maven-local'
    targetDeploySnapshotRepo: 'web-maven-snapshots-local'
    collectBuildInfo: true
    buildName: '$(Build.DefinitionName)'
    buildNumber: '$(Build.BuildNumber)'
- task: ArtifactoryPublishBuildInfo@1
  inputs:
    artifactoryService: 'JFrog'
    buildName: '$(Build.DefinitionName)'
    buildNumber: '$(Build.BuildNumber)'